config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :teachers
  resources :lessons
  resources :students
  resources :users, only: [:update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "lessons#index"

  get "/lessons" , to: "lessons#index"
  get "/teachers" , to: "teachers#index"
  get "/students" , to: "students#index"

  get "/users/sign_out", to: "sessions#destroy"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	has_many :student
	has_many :teacher
	validates :subject, presence: true
	validates :level, presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
    @students = Student.all
    @teachers = Teacher.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @students = Student.all
    @teachers = Teacher.all
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @students = Student.all
    @teachers = Teacher.all
    authorize @lesson
  end

  # GET /lessons/1/edit
  def edit
    @students = Student.all
    @teachers = Teacher.all
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @students = Student.all
    @teachers = Teacher.all
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    @students = Student.all
    @teachers = Teacher.all
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
  authorize @lesson, :update?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:subject, :level, :teacher_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :lesson_subject %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :lesson_level %>
  </div>

  <div class="field">
    <%= form.collection_select(:teacher_id, Teacher.all, :id, :name, { :prompt => 'Teacher', :selected => :teacher_id}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Subject</th>
      <th>Level</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.id %></td>
        <td><%= lesson.subject %></td>
        <td><%= lesson.level %></td>
        <td><%= lesson.teacher_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <% if policy(lesson).destroy? %>
          <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

        <!-- <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @lesson.subject %>
</p>

<p>
  <strong>Level:</strong>
  <%= @lesson.level %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @lesson.teacher_id %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>